#!/bin/bash
set -e

# Set environment variables
export HOME="${BACKUP_DATA_DIR}"
echo "${HOME}" > "/etc/container_environment/HOME"

# Check if we are triggering a single backup otherwise trigger a full initialization
case "$1" in
  "backup"|"trigger" )
    # Extract the backup task argument and execute it
    shift
    command="trigger-backup $@"
    ;;
  * )
    command="$@"
    ;;
esac

${command}
