#!/bin/bash
set -e

# Check if we are triggering a single backup otherwise trigger a full initialization
case "$1" in
  "backup"|"trigger" )
    # Extract the backup task argument and execute it
    shift
    command="trigger-backup $@"
    ;;
  * )
    command="$@"
    ;;
esac

${command}
